<#
.SYNOPSIS
    Creates a new development plan with AI-assisted ideation.

.DESCRIPTION
    Provides interactive or non-interactive plan creation. Supports AI ideation
    to generate epics and tasks from project goals, with feedback loops for
    refinement. Outputs a structured plan file.

    Replaces: plan.sh (create mode)

.PARAMETER ProjectDir
    Project root directory.
.PARAMETER Goal
    High-level project goal for AI ideation.
.PARAMETER PlanFile
    Path to write the plan. Default: <ProjectDir>/plan-<timestamp>.md
.PARAMETER NonInteractive
    Skip interactive prompts and use defaults.

.EXAMPLE
    ./New-Plan.ps1 -ProjectDir "/project" -Goal "Implement user auth with JWT" -NonInteractive
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$ProjectDir,

    [string]$Goal = '',

    [string]$PlanFile = '',

    [switch]$NonInteractive
)

# --- Resolve paths ---
$agentsDir = Join-Path $ProjectDir ".agents"
if (-not (Test-Path $agentsDir)) { $agentsDir = $PSScriptRoot | Split-Path }

# --- Generate plan file name ---
if (-not $PlanFile) {
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $PlanFile = Join-Path $ProjectDir "plan-$timestamp.md"
}

# --- Interactive goal prompt ---
if (-not $Goal -and -not $NonInteractive) {
    Write-Host ""
    Write-Host "=== Ostwin Plan Creator ===" -ForegroundColor Cyan
    Write-Host ""
    $Goal = Read-Host "What is the goal of this plan?"
}

if (-not $Goal) {
    Write-Error "No goal provided. Use -Goal parameter or interactive mode."
    exit 1
}

# --- Build plan structure ---
$planContent = @"
# Plan: $Goal

> Created: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ' -AsUTC)
> Status: draft
> Project: $ProjectDir

---

## Goal

$Goal

## Epics

### EPIC-001 — $Goal

#### Definition of Done
- [ ] Core functionality implemented
- [ ] Unit tests passing with >= 80% coverage
- [ ] Code reviewed and documented

#### Acceptance Criteria
- [ ] All specified features are working
- [ ] No critical or high-severity bugs
- [ ] Performance meets requirements

#### Tasks
- [ ] TASK-001 — Design and plan implementation
- [ ] TASK-002 — Implement core functionality
- [ ] TASK-003 — Write unit tests
- [ ] TASK-004 — Documentation and cleanup

---

## Configuration

``````json
{
    "plan_id": "plan-$(Get-Date -Format 'yyyyMMdd-HHmmss')",
    "priority": 1,
    "goals": {
        "definition_of_done": [
            "Core functionality implemented",
            "Unit tests passing with >= 80% coverage",
            "Code reviewed and documented"
        ],
        "acceptance_criteria": [
            "All specified features are working",
            "No critical or high-severity bugs",
            "Performance meets requirements"
        ]
    }
}
``````

---

## Notes

_This plan was generated by Ostwin. Review and refine before starting._
"@

# --- Write plan ---
$planContent | Out-File -FilePath $PlanFile -Encoding utf8

Write-Host ""
Write-Host "[PLAN] Created: $PlanFile" -ForegroundColor Green
Write-Host "[PLAN] Goal: $Goal"
Write-Host "[PLAN] Epics: 1"
Write-Host "[PLAN] Tasks: 4"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Review and edit the plan"
Write-Host "  2. Run: ./Start-Plan.ps1 -PlanFile '$PlanFile'"

Write-Output $PlanFile
