#!/usr/bin/env bash
# Draft RELEASE.md from all completed war-rooms
#
# Usage: draft.sh <agents-dir>
#
# Reads all "pass" messages across war-rooms and compiles release notes.

set -euo pipefail

AGENTS_DIR="${1:-.agents}"
CHANNEL="$AGENTS_DIR/channel"
WARROOMS="$AGENTS_DIR/war-rooms"
TEMPLATE="$AGENTS_DIR/release/RELEASE.template.md"
OUTPUT="$AGENTS_DIR/RELEASE.md"

VERSION="v0.1.0-$(date +%Y%m%d)"
DATE=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

echo "[RELEASE] Drafting release notes..."

# Collect task sections
TASK_SECTIONS=""
TASK_COUNT=0

for room_dir in "$WARROOMS"/room-*/; do
  [[ -d "$room_dir" ]] || continue

  status=$(cat "$room_dir/status" 2>/dev/null || echo "unknown")
  task_ref=$(cat "$room_dir/task-ref" 2>/dev/null || echo "UNKNOWN")
  room_id=$(basename "$room_dir")

  # Read brief description (first line header)
  task_title=$(head -1 "$room_dir/brief.md" 2>/dev/null | sed 's/^# //' || echo "$task_ref")

  # Read QA verdict
  qa_verdict=$("$CHANNEL/read.sh" "$room_dir" --type pass --last 1 2>/dev/null | \
    python3 -c "
import json, sys
msgs = json.load(sys.stdin)
if msgs:
    body = msgs[-1].get('body', 'Approved')
    # Truncate long verdicts
    lines = body.split('\n')[:5]
    print('\n'.join(lines))
else:
    print('No QA verdict recorded')
" 2>/dev/null || echo "N/A")

  TASK_SECTIONS="${TASK_SECTIONS}
### $task_ref — $task_title

- **Room**: $room_id
- **Status**: $status
- **QA Verdict**: $qa_verdict
"
  TASK_COUNT=$((TASK_COUNT + 1))
done

SUMMARY="$TASK_COUNT task(s) completed and reviewed by QA."

# Build release notes from template
if [[ -f "$TEMPLATE" ]]; then
  sed -e "s|{{VERSION}}|$VERSION|g" \
      -e "s|{{DATE}}|$DATE|g" \
      -e "s|{{STATUS}}|Draft|g" \
      -e "s|{{SUMMARY}}|$SUMMARY|g" \
      "$TEMPLATE" | \
    python3 -c "
import sys
content = sys.stdin.read()
task_sections = '''$TASK_SECTIONS'''
content = content.replace('{{TASK_SECTIONS}}', task_sections)
content = content.replace('{{SIGNOFF_ROWS}}', '| Manager | Pending | - |\n| Engineer | Pending | - |\n| QA | Pending | - |')
print(content)
" > "$OUTPUT"
else
  # Fallback: generate without template
  cat > "$OUTPUT" << EOF
# Release: $VERSION

**Date**: $DATE
**Status**: Draft

## Summary

$SUMMARY

## Tasks Completed

$TASK_SECTIONS

## Sign-offs

| Role     | Status  | Timestamp |
|----------|---------|-----------|
| Manager  | Pending | -         |
| Engineer | Pending | -         |
| QA       | Pending | -         |

---

*Generated by Agent OS*
EOF
fi

echo "[RELEASE] Draft written to: $OUTPUT"
echo "[RELEASE] $TASK_COUNT tasks included."
